@entrypoint=http://localhost:5555/api/v1

@accessToken=Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjUsImVtYWlsIjoidXNzb3BAdGVzdC5jb20iLCJsYXN0X25hbWUiOiJTbmlwZXJraW5nIiwiZmlyc3RfbmFtZSI6IlVzc29wIiwiaXNfYWRtaW4iOnRydWUsImlhdCI6MTY3NDAzMzI0OCwiZXhwIjoxNjc0MTE5NjQ4fQ.yowLwo_7R6tf2byGaUZbecTYjPgdY1sRuOjiODUgoNE

@refreshToken=Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjIsImVtYWlsIjoiYWRtaW5AdGVzdC5jb20iLCJsYXN0X25hbWUiOiJTdXBlciBBZG1pbiIsImZpcnN0X25hbWUiOiJHYWV0YW4iLCJpYXQiOjE2NzM3MDQ2MjQsImV4cCI6MTY3Mzg3NzQyNH0.Hm8yDWYI_Tm2WCwXuAf22J3rnEZcCqouATmiYG6cn-Q


#! ----------------------------------------------------------------
#! ---------------------------------------------------------------- User Routes
#! ----------------------------------------------------------------
###
#----------------------------------------------------- Get All Users
GET {{entrypoint}}/users

###
#----------------------------------------------------- Create User
POST {{entrypoint}}/users/signup
Content-Type: application/json

{
    "email": "ussop@test.com",
    "password": "blaBla83!!",
    "last_name": "Sniperking",
    "first_name": "Ussop",
    "is_admin": true
}

###
#----------------------------------------------------- User connection
POST {{entrypoint}}/users/signin
Content-Type: application/json

{
    "email": "ussop@test.com",
    "password": "blaBla83!!"
}

###
#----------------------------------------------------- Get User Profil with Auth
GET {{entrypoint}}/users/23
{{accessToken}}

###
#----------------------------------------------------- Update User
PATCH {{entrypoint}}/users/23
Content-Type: application/json
{{accessToken}}

{
  "id": 23,
  "location": {
      "label": " 25 Grand line, 83100 South Blue",
      "address": "Grand Line Sea",
      "street_number": 2,
      "zipcode": 83000,
      "city": "East Blue",
      "lat": 100.48321312548,
      "lon": -40.1242312913
    }
}

###
#----------------------------------------------------- Delete User
DELETE {{entrypoint}}/users/21
{{accessToken}}

#? ----------------------------------------------------------------
#? ---------------------------------------------------------------- Locations Routes
#? ----------------------------------------------------------------

###
#----------------------------------------------------- Get All Locations
GET {{entrypoint}}/locations

###
#----------------------------------------------------- Get One Location
GET {{entrypoint}}/locations/96

###
#----------------------------------------------------- Create Location
POST {{entrypoint}}/locations
Content-Type: application/json

{

    "label": " 25 Grand line, 83100 South Blue",
    "address": "test trest",
    "street_number": 2,
    "zipcode": 83000,
    "city": "East Blue",
    "lat":0.48321312548,
    "lon": -0.1242312913
}
###
#----------------------------------------------------- Update Location
PATCH {{entrypoint}}/locations/50
Content-Type: application/json

Content-Type: application/json

{
    
    "label": " 25 Grand line, 83100 South Blue",
    "address": "test trest",
    "street_number": 2,
    "zipcode": 83000,
    "city": "East Blue",
    "lat":0.48321312548,
    "lon": -0.1242312913
}

###
#----------------------------------------------------- Delete Location
DELETE {{entrypoint}}/locations/49

#* ----------------------------------------------------------------
#* ---------------------------------------------------------------- Categories Routes
#* ----------------------------------------------------------------

#~ ----------------------------------------------------------------
#~ ---------------------------------------------------------------- Vehicules Routes
#~ ----------------------------------------------------------------