BEGIN;

CREATE DOMAIN EMAIL AS TEXT CHECK ( value ~ '^[\w\-\.]+@([\w-]+\.)+[\w-]+$');

CREATE DOMAIN PASSWORD AS TEXT CHECK ( value ~ '^(?=.*\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[a-zA-Z]).{6,}$');

CREATE DOMAIN postal_code_fr AS text CHECK (
    -- 01000 à 09999
    VALUE ~ '0[1-9]\d{3}' 
    -- 10000 à 89999
    OR VALUE ~ '[1-8]\d{4}' 
    -- les numéros commençant par 9 en métropole
    OR VALUE ~ '9[0-6]\d{3}'
);


CREATE TABLE
    IF NOT EXISTS public."user"(
        "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "email" EMAIL UNIQUE NOT NULL,
        "password" TEXT NOT NULL,
        "last_name" TEXT NOT NULL,
        "first_name" TEXT NOT NULL,
        "location_id" INT NULL,
        "vehicle_id" INT NULL,
        "created_at" timestamptz NOT NULL DEFAULT NOW(),
        "updated_at" timestamptz
    );

CREATE TABLE
    IF NOT EXISTS public."network"(
        "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "name" TEXT NOT NULL UNIQUE,
        "image" TEXT NULL,
        "created_at" timestamptz NOT NULL DEFAULT NOW(),
        "updated_at" timestamptz
    );

CREATE TABLE
    IF NOT EXISTS public."vehicle"(
        "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "registration" TEXT NOT NULL,
        "brand_id" INT NOT NULL,
        "model" TEXT NOT NULL UNIQUE,
        "image" TEXT NULL,
        "network_id" INT NULL REFERENCES "network" ("id"),
        "created_at" timestamptz NOT NULL DEFAULT NOW(),
        "updated_at" timestamptz
    );


CREATE TABLE
    IF NOT EXISTS public."location"(
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "label" TEXT NULL,
    "street_number" INT NULL,
    "address" TEXT NOT NULL,
    "zipcode" postal_code_fr NOT NULL,
    "city" TEXT NOT NULL,
    "lat" NUMERIC NOT NULL,
    "lon" NUMERIC NOT NULL
);

CREATE TABLE
    IF NOT EXISTS public."category"(
        "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "name" TEXT NOT NULL UNIQUE,
        "icon" TEXT NOT NULL,
        "created_at" timestamptz NOT NULL DEFAULT NOW(),
        "updated_at" timestamptz
    );


CREATE TABLE
    IF NOT EXISTS public."charging_station" (
        "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "network_id" INT NULL REFERENCES "network" ("id"),
        "location_id" INT NOT NULL REFERENCES "location"("id"),
        "created_at" timestamptz NOT NULL DEFAULT NOW(),
        "updated_at" timestamptz
    );

CREATE TABLE
    IF NOT EXISTS public."interesting_point" (
        "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "name" TEXT NOT NULL UNIQUE,
        "description" TEXT NULL,
        "image" TEXT NULL,
        "eco_friendly" BOOLEAN DEFAULT FALSE,
        "category_id" INT NOT NULL REFERENCES "category"("id"),
        "location_id" INT NOT NULL REFERENCES "location"("id"),
        "created_at" timestamptz NOT NULL DEFAULT NOW(),
        "updated_at" timestamptz
    );

CREATE TABLE
    IF NOT EXISTS public."road" (
        "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "user_id" INT NOT NULL REFERENCES "user"("id"),
        "generated_road" JSON NULL,
        "favorite" BOOLEAN DEFAULT FALSE,
        "created_at" timestamptz NOT NULL DEFAULT NOW(),
        "updated_at" timestamptz
    );

CREATE TABLE
    IF NOT EXISTS public."user_like_category"(
        "category_id" INT REFERENCES "category"("id"),
        "user_id" INT REFERENCES "user"("id"),
    );

CREATE TABLE 
    IF NOT EXISTS public."user_has_location"(
        "location_id" INT REFERENCES "location"("id"),
        "user_id" INT REFERENCES "user"("id")
    )

CREATE TABLE
    IF NOT EXISTS public."brand"(
        "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "name" TEXT NOT NULL UNIQUE,
        "created_at" timestamptz NOT NULL DEFAULT NOW(),
        "updated_at" timestamptz
    );

ALTER TABLE "vehicle" ADD FOREIGN KEY ("brand_id") REFERENCES "brand"("id"); 
ALTER TABLE "user" ADD FOREIGN KEY ("vehicle_id") REFERENCES "vehicle"("id"); 
ALTER TABLE "user" ADD FOREIGN KEY ("location_id") REFERENCES "location"("id");
ALTER TABLE "user" ADD COLUMN "is_admin" BOOLEAN NOT NULL DEFAULT false;


COMMIT;